nmMode: classic

nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN:-}'

npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  redoc-cli@*:
    dependencies:
      '@redocly/openapi-core': 1.0.0-beta.104
  redoc@*:
    dependencies:
      call-me-maybe: '*'
      fast-safe-stringify: '*'
      yaml: '*'
  styled-components@*:
    dependencies:
      react-is: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
